/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/upload/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an image (internal API, requires X-Api-Key).
         *     Pipeline: validate → SkiaSharp decode → resize (max 4000px) → encode webp → SHA-256 dedup.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an avatar image (internal API, requires X-Api-Key).
         *     Same pipeline as M:Drink.Upload.API.Controllers.FilesController.Upload(Microsoft.AspNetCore.Http.IFormFile,System.Threading.CancellationToken) but resized to max 512px long edge.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            data?: unknown;
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        FileUploadResponse: {
            path?: string | null;
            hash?: string | null;
            /** Format: int64 */
            size?: number;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            mime_type?: string | null;
        };
        FileUploadResponseApiResponse: {
            data?: components["schemas"]["FileUploadResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
