/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 註冊（送出後會寄出 Email 驗證信） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRegisterRequest"];
                    "text/json": components["schemas"]["UserRegisterRequest"];
                    "application/*+json": components["schemas"]["UserRegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 驗證 Email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserVerifyEmailRequest"];
                    "text/json": components["schemas"]["UserVerifyEmailRequest"];
                    "application/*+json": components["schemas"]["UserVerifyEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登入 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserLoginRequest"];
                    "text/json": components["schemas"]["UserLoginRequest"];
                    "application/*+json": components["schemas"]["UserLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserLoginResponseApiResponse"];
                        "application/json": components["schemas"]["UserLoginResponseApiResponse"];
                        "text/json": components["schemas"]["UserLoginResponseApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 Token（Refresh Token Rotation） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRefreshTokenRequest"];
                    "text/json": components["schemas"]["UserRefreshTokenRequest"];
                    "application/*+json": components["schemas"]["UserRefreshTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserLoginResponseApiResponse"];
                        "application/json": components["schemas"]["UserLoginResponseApiResponse"];
                        "text/json": components["schemas"]["UserLoginResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（撤銷 refresh_token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserLogoutRequest"];
                    "text/json": components["schemas"]["UserLogoutRequest"];
                    "application/*+json": components["schemas"]["UserLogoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 變更密碼（成功後撤銷該用戶所有 refresh token） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangeUserPasswordRequest"];
                    "text/json": components["schemas"]["ChangeUserPasswordRequest"];
                    "application/*+json": components["schemas"]["ChangeUserPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出所有裝置（撤銷該用戶所有 refresh token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    SortBy?: string;
                    SortOrder?: string;
                    Keyword?: string;
                    ShopId?: number;
                    Scope?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserOrderListItemResponsePaginationListApiResponse"];
                        "application/json": components["schemas"]["UserOrderListItemResponsePaginationListApiResponse"];
                        "text/json": components["schemas"]["UserOrderListItemResponsePaginationListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateGroupOrderRequest"];
                    "text/json": components["schemas"]["CreateGroupOrderRequest"];
                    "application/*+json": components["schemas"]["CreateGroupOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Int32ApiResponse"];
                        "application/json": components["schemas"]["Int32ApiResponse"];
                        "text/json": components["schemas"]["Int32ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserOrderDetailResponseApiResponse"];
                        "application/json": components["schemas"]["UserOrderDetailResponseApiResponse"];
                        "text/json": components["schemas"]["UserOrderDetailResponseApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateGroupOrderRequest"];
                    "text/json": components["schemas"]["UpdateGroupOrderRequest"];
                    "application/*+json": components["schemas"]["UpdateGroupOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/orders/{groupOrderId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupOrderId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrderItemRequest"];
                    "text/json": components["schemas"]["CreateOrderItemRequest"];
                    "application/*+json": components["schemas"]["CreateOrderItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Int32ApiResponse"];
                        "application/json": components["schemas"]["Int32ApiResponse"];
                        "text/json": components["schemas"]["Int32ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/orders/{groupOrderId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupOrderId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderItemRequest"];
                    "text/json": components["schemas"]["UpdateOrderItemRequest"];
                    "application/*+json": components["schemas"]["UpdateOrderItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupOrderId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得個人資料 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileResponseApiResponse"];
                        "application/json": components["schemas"]["UserProfileResponseApiResponse"];
                        "text/json": components["schemas"]["UserProfileResponseApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        /** 更新個人資料（name / avatar / notification_type） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserProfileRequest"];
                    "text/json": components["schemas"]["UpdateUserProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateUserProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileResponseApiResponse"];
                        "application/json": components["schemas"]["UserProfileResponseApiResponse"];
                        "text/json": components["schemas"]["UserProfileResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上傳圖片（proxy 至 Upload.API；單檔，多檔由前端佇列序列呼叫） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/upload/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上傳頭像（proxy 至 Upload.API /api/upload/avatar；max 長邊 512px） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/upload/asset-host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得圖片資產的 base URL（前端拼接圖片 URL 用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AssetHostResponseApiResponse"];
                        "application/json": components["schemas"]["AssetHostResponseApiResponse"];
                        "text/json": components["schemas"]["AssetHostResponseApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            data?: unknown;
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        AssetHostResponse: {
            base_url?: string | null;
        };
        AssetHostResponseApiResponse: {
            data?: components["schemas"]["AssetHostResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        ChangeUserPasswordRequest: {
            old_password: string;
            new_password: string;
        };
        CreateGroupOrderRequest: {
            title: string;
            /** Format: int32 */
            shop_id: number;
            /** Format: date-time */
            deadline: string;
            note?: string | null;
        };
        CreateOrderItemRequest: {
            recipient_name: string;
            /** Format: int32 */
            menu_item_id: number;
            /** Format: int32 */
            size_id: number;
            /** Format: int32 */
            sugar_id: number;
            /** Format: int32 */
            ice_id: number;
            topping_ids?: number[] | null;
            /** Format: int32 */
            quantity?: number;
            note?: string | null;
        };
        FileUploadResponse: {
            path?: string | null;
            hash?: string | null;
            /** Format: int64 */
            size?: number;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            mime_type?: string | null;
        };
        FileUploadResponseApiResponse: {
            data?: components["schemas"]["FileUploadResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        GroupOrderStatus: 1 | 2 | 3 | 4 | 5;
        Int32ApiResponse: {
            /** Format: int32 */
            data?: number;
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        NotificationType: 0 | 1 | 2 | 3;
        UpdateGroupOrderRequest: {
            title: string;
            /** Format: date-time */
            deadline: string;
            note?: string | null;
        };
        UpdateOrderItemRequest: {
            recipient_name: string;
            /** Format: int32 */
            menu_item_id: number;
            /** Format: int32 */
            size_id: number;
            /** Format: int32 */
            sugar_id: number;
            /** Format: int32 */
            ice_id: number;
            topping_ids?: number[] | null;
            /** Format: int32 */
            quantity?: number;
            note?: string | null;
        };
        UpdateUserProfileRequest: {
            name: string;
            avatar?: string | null;
            notification_type: components["schemas"]["NotificationType"];
        };
        UserLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserLoginResponse: {
            access_token?: string | null;
            refresh_token?: string | null;
        };
        UserLoginResponseApiResponse: {
            data?: components["schemas"]["UserLoginResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        UserLogoutRequest: {
            refresh_token: string;
        };
        UserOrderDetailResponse: {
            /** Format: int32 */
            id?: number;
            title?: string | null;
            /** Format: int32 */
            shop_id?: number;
            shop_name?: string | null;
            initiator_name?: string | null;
            is_mine?: boolean;
            status?: components["schemas"]["GroupOrderStatus"];
            /** Format: date-time */
            deadline?: string;
            note?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            order_items?: components["schemas"]["UserOrderItemResponse"][] | null;
            summary?: components["schemas"]["UserOrderSummary"];
        };
        UserOrderDetailResponseApiResponse: {
            data?: components["schemas"]["UserOrderDetailResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        UserOrderItemResponse: {
            /** Format: int32 */
            id?: number;
            user_name?: string | null;
            recipient_name?: string | null;
            menu_item_name?: string | null;
            size_name?: string | null;
            sugar_name?: string | null;
            ice_name?: string | null;
            toppings?: components["schemas"]["UserOrderItemToppingResponse"][] | null;
            /** Format: double */
            item_price?: number;
            /** Format: double */
            sugar_price?: number;
            /** Format: double */
            topping_price?: number;
            /** Format: double */
            total_price?: number;
            /** Format: int32 */
            quantity?: number;
            note?: string | null;
            is_mine?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UserOrderItemToppingResponse: {
            topping_name?: string | null;
            /** Format: double */
            price?: number;
        };
        UserOrderListItemResponse: {
            /** Format: int32 */
            id?: number;
            title?: string | null;
            /** Format: int32 */
            shop_id?: number;
            shop_name?: string | null;
            initiator_name?: string | null;
            status?: components["schemas"]["GroupOrderStatus"];
            /** Format: date-time */
            deadline?: string;
            /** Format: int32 */
            order_item_count?: number;
            /** Format: double */
            total_amount?: number;
            is_mine?: boolean;
            is_joined?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UserOrderListItemResponsePaginationList: {
            items?: components["schemas"]["UserOrderListItemResponse"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            page_size?: number;
        };
        UserOrderListItemResponsePaginationListApiResponse: {
            data?: components["schemas"]["UserOrderListItemResponsePaginationList"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        UserOrderSummary: {
            /** Format: int32 */
            total_items?: number;
            /** Format: double */
            total_amount?: number;
            /** Format: int32 */
            recipient_count?: number;
        };
        UserProfileResponse: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            email?: string | null;
            avatar?: string | null;
            notification_type?: components["schemas"]["NotificationType"];
            is_google_connected?: boolean;
            email_verified?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UserProfileResponseApiResponse: {
            data?: components["schemas"]["UserProfileResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        UserRefreshTokenRequest: {
            refresh_token: string;
        };
        UserRegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        UserVerifyEmailRequest: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
