/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上傳檔案（proxy 至 Upload.API） */
        post: {
            parameters: {
                query?: {
                    /** @description 分類資料夾（如 images, pdf） */
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description 檔案
                         */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            data?: unknown;
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        FileUploadResponse: {
            file_name?: string | null;
            url?: string | null;
            content_type?: string | null;
            /** Format: int64 */
            file_size?: number;
        };
        FileUploadResponseApiResponse: {
            data?: components["schemas"]["FileUploadResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
