/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上傳圖片（proxy 至 Upload.API；單檔，多檔由前端佇列序列呼叫） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileUploadResponseApiResponse"];
                        "application/json": components["schemas"]["FileUploadResponseApiResponse"];
                        "text/json": components["schemas"]["FileUploadResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/upload/asset-host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得圖片資產的 base URL（前端拼接圖片 URL 用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AssetHostResponseApiResponse"];
                        "application/json": components["schemas"]["AssetHostResponseApiResponse"];
                        "text/json": components["schemas"]["AssetHostResponseApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            data?: unknown;
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        AssetHostResponse: {
            base_url?: string | null;
        };
        AssetHostResponseApiResponse: {
            data?: components["schemas"]["AssetHostResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        FileUploadResponse: {
            path?: string | null;
            hash?: string | null;
            /** Format: int64 */
            size?: number;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            mime_type?: string | null;
        };
        FileUploadResponseApiResponse: {
            data?: components["schemas"]["FileUploadResponse"];
            message?: string | null;
            /** Format: int32 */
            code?: number;
            error?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
