// <auto-generated />
using System;
using Drink.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drink.Infrastructure.Migrations
{
    [DbContext(typeof(DrinkDbContext))]
    [Migration("20260329181405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_menu");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_admin_menu_parent_id");

                    b.ToTable("admin_menu", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_menu_role");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_admin_menu_role_menu_id");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_menu_role_role_id_menu_id");

                    b.ToTable("admin_menu_role", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_admin_refresh_token_user_id");

                    b.ToTable("admin_refresh_token", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_role");

                    b.ToTable("admin_role", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_admin_user_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_user_username");

                    b.ToTable("admin_user", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_menu_admin_menu_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenuRole", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminMenu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_menu_role_admin_menu_menu_id");

                    b.HasOne("Drink.Domain.Entities.AdminRole", "Role")
                        .WithMany("MenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_menu_role_admin_role_role_id");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_refresh_token_admin_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_user_admin_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRole", b =>
                {
                    b.Navigation("MenuRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
