// <auto-generated />
using System;
using Drink.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drink.Infrastructure.Migrations
{
    [DbContext(typeof(DrinkDbContext))]
    [Migration("20260427171549_AddAdminMenuIsPermissionOnly")]
    partial class AddAdminMenuIsPermissionOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsPermissionOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_permission_only");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_menu");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_admin_menu_parent_id");

                    b.ToTable("admin_menu", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_menu_role");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_admin_menu_role_menu_id");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_menu_role_role_id_menu_id");

                    b.ToTable("admin_menu_role", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_admin_refresh_token_user_id");

                    b.ToTable("admin_refresh_token", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_admin_role");

                    b.ToTable("admin_role", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_admin_user_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_user_username");

                    b.ToTable("admin_user", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.DrinkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_drink_item");

                    b.ToTable("drink_item", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.Ice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_ice");

                    b.ToTable("ice", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxToppingPerItem")
                        .HasColumnType("integer")
                        .HasColumnName("max_topping_per_item");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_category");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_category_shop_id");

                    b.ToTable("shop_category", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledIce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("IceId")
                        .HasColumnType("integer")
                        .HasColumnName("ice_id");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_enabled_ice");

                    b.HasIndex("IceId")
                        .HasDatabaseName("ix_shop_enabled_ice_ice_id");

                    b.HasIndex("ShopId", "IceId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_enabled_ice_shop_id_ice_id");

                    b.ToTable("shop_enabled_ice", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer")
                        .HasColumnName("size_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_enabled_size");

                    b.HasIndex("SizeId")
                        .HasDatabaseName("ix_shop_enabled_size_size_id");

                    b.HasIndex("ShopId", "SizeId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_enabled_size_shop_id_size_id");

                    b.ToTable("shop_enabled_size", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledSugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<int>("SugarId")
                        .HasColumnType("integer")
                        .HasColumnName("sugar_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_enabled_sugar");

                    b.HasIndex("SugarId")
                        .HasDatabaseName("ix_shop_enabled_sugar_sugar_id");

                    b.HasIndex("ShopId", "SugarId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_enabled_sugar_shop_id_sugar_id");

                    b.ToTable("shop_enabled_sugar", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<int>("ToppingId")
                        .HasColumnType("integer")
                        .HasColumnName("topping_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_enabled_topping");

                    b.HasIndex("ToppingId")
                        .HasDatabaseName("ix_shop_enabled_topping_topping_id");

                    b.HasIndex("ShopId", "ToppingId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_enabled_topping_shop_id_topping_id");

                    b.ToTable("shop_enabled_topping", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int?>("DrinkItemId")
                        .HasColumnType("integer")
                        .HasColumnName("drink_item_id");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("path");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_shop_image");

                    b.HasIndex("DrinkItemId")
                        .HasDatabaseName("ix_shop_image_drink_item_id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_shop_image_hash");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_image_shop_id")
                        .HasFilter("drink_item_id IS NULL");

                    b.HasIndex("ShopId", "DrinkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_image_shop_id_drink_item_id")
                        .HasFilter("is_cover = true");

                    b.HasIndex("ShopId", "DrinkItemId", "Sort")
                        .HasDatabaseName("ix_shop_image_shop_id_drink_item_id_sort");

                    b.ToTable("shop_image", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("DrinkItemId")
                        .HasColumnType("integer")
                        .HasColumnName("drink_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxToppingCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_topping_count");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_menu_item");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_shop_menu_item_category_id");

                    b.HasIndex("DrinkItemId")
                        .HasDatabaseName("ix_shop_menu_item_drink_item_id");

                    b.ToTable("shop_menu_item", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemIce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("IceId")
                        .HasColumnType("integer")
                        .HasColumnName("ice_id");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_menu_item_ice");

                    b.HasIndex("IceId")
                        .HasDatabaseName("ix_shop_menu_item_ice_ice_id");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_shop_menu_item_ice_menu_item_id");

                    b.ToTable("shop_menu_item_ice", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer")
                        .HasColumnName("size_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_menu_item_size");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_shop_menu_item_size_menu_item_id");

                    b.HasIndex("SizeId")
                        .HasDatabaseName("ix_shop_menu_item_size_size_id");

                    b.ToTable("shop_menu_item_size", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemSugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("SugarId")
                        .HasColumnType("integer")
                        .HasColumnName("sugar_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_menu_item_sugar");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_shop_menu_item_sugar_menu_item_id");

                    b.HasIndex("SugarId")
                        .HasDatabaseName("ix_shop_menu_item_sugar_sugar_id");

                    b.ToTable("shop_menu_item_sugar", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("ToppingId")
                        .HasColumnType("integer")
                        .HasColumnName("topping_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_menu_item_topping");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_shop_menu_item_topping_menu_item_id");

                    b.HasIndex("ToppingId")
                        .HasDatabaseName("ix_shop_menu_item_topping_topping_id");

                    b.ToTable("shop_menu_item_topping", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopSugarOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("SugarId")
                        .HasColumnType("integer")
                        .HasColumnName("sugar_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_sugar_override");

                    b.HasIndex("SugarId")
                        .HasDatabaseName("ix_shop_sugar_override_sugar_id");

                    b.HasIndex("ShopId", "SugarId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_sugar_override_shop_id_sugar_id");

                    b.ToTable("shop_sugar_override", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopToppingOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<int>("ToppingId")
                        .HasColumnType("integer")
                        .HasColumnName("topping_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_shop_topping_override");

                    b.HasIndex("ToppingId")
                        .HasDatabaseName("ix_shop_topping_override_topping_id");

                    b.HasIndex("ShopId", "ToppingId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_topping_override_shop_id_topping_id");

                    b.ToTable("shop_topping_override", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_size");

                    b.ToTable("size", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.Sugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("default_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_sugar");

                    b.ToTable("sugar", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("default_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_topping");

                    b.ToTable("topping", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsGoogleConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_google_connected");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_refresh_token_user_id");

                    b.ToTable("user_refresh_token", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.VerificationEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Creator")
                        .HasColumnType("integer")
                        .HasColumnName("creator");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Updater")
                        .HasColumnType("integer")
                        .HasColumnName("updater");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verification_email");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_email_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_verification_email_user_id");

                    b.ToTable("verification_email", (string)null);
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_menu_admin_menu_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenuRole", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminMenu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_menu_role_admin_menu_menu_id");

                    b.HasOne("Drink.Domain.Entities.AdminRole", "Role")
                        .WithMany("MenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_menu_role_admin_role_role_id");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_refresh_token_admin_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("Drink.Domain.Entities.AdminRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_user_admin_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopCategory", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("Categories")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_category_shop_shop_id");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledIce", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Ice", "Ice")
                        .WithMany()
                        .HasForeignKey("IceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_ice_ice_ice_id");

                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("EnabledIces")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_ice_shop_shop_id");

                    b.Navigation("Ice");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledSize", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("EnabledSizes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_size_shop_shop_id");

                    b.HasOne("Drink.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_size_size_size_id");

                    b.Navigation("Shop");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledSugar", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("EnabledSugars")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_sugar_shop_shop_id");

                    b.HasOne("Drink.Domain.Entities.Sugar", "Sugar")
                        .WithMany()
                        .HasForeignKey("SugarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_sugar_sugar_sugar_id");

                    b.Navigation("Shop");

                    b.Navigation("Sugar");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopEnabledTopping", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("EnabledToppings")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_topping_shop_shop_id");

                    b.HasOne("Drink.Domain.Entities.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_enabled_topping_topping_topping_id");

                    b.Navigation("Shop");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopImage", b =>
                {
                    b.HasOne("Drink.Domain.Entities.DrinkItem", "DrinkItem")
                        .WithMany()
                        .HasForeignKey("DrinkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shop_image_drink_item_drink_item_id");

                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_image_shop_shop_id");

                    b.Navigation("DrinkItem");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItem", b =>
                {
                    b.HasOne("Drink.Domain.Entities.ShopCategory", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_shop_category_category_id");

                    b.HasOne("Drink.Domain.Entities.DrinkItem", "DrinkItem")
                        .WithMany()
                        .HasForeignKey("DrinkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_drink_item_drink_item_id");

                    b.Navigation("Category");

                    b.Navigation("DrinkItem");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemIce", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Ice", "Ice")
                        .WithMany()
                        .HasForeignKey("IceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_ice_ice_ice_id");

                    b.HasOne("Drink.Domain.Entities.ShopMenuItem", "MenuItem")
                        .WithMany("Ices")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_ice_shop_menu_item_menu_item_id");

                    b.Navigation("Ice");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemSize", b =>
                {
                    b.HasOne("Drink.Domain.Entities.ShopMenuItem", "MenuItem")
                        .WithMany("Sizes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_size_shop_menu_item_menu_item_id");

                    b.HasOne("Drink.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_size_size_size_id");

                    b.Navigation("MenuItem");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemSugar", b =>
                {
                    b.HasOne("Drink.Domain.Entities.ShopMenuItem", "MenuItem")
                        .WithMany("Sugars")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_sugar_shop_menu_item_menu_item_id");

                    b.HasOne("Drink.Domain.Entities.Sugar", "Sugar")
                        .WithMany()
                        .HasForeignKey("SugarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_sugar_sugar_sugar_id");

                    b.Navigation("MenuItem");

                    b.Navigation("Sugar");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItemTopping", b =>
                {
                    b.HasOne("Drink.Domain.Entities.ShopMenuItem", "MenuItem")
                        .WithMany("Toppings")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_topping_shop_menu_item_menu_item_id");

                    b.HasOne("Drink.Domain.Entities.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_menu_item_topping_topping_topping_id");

                    b.Navigation("MenuItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopSugarOverride", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("SugarOverrides")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_sugar_override_shop_shop_id");

                    b.HasOne("Drink.Domain.Entities.Sugar", "Sugar")
                        .WithMany()
                        .HasForeignKey("SugarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_sugar_override_sugar_sugar_id");

                    b.Navigation("Shop");

                    b.Navigation("Sugar");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopToppingOverride", b =>
                {
                    b.HasOne("Drink.Domain.Entities.Shop", "Shop")
                        .WithMany("ToppingOverrides")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_topping_override_shop_shop_id");

                    b.HasOne("Drink.Domain.Entities.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_topping_override_topping_topping_id");

                    b.Navigation("Shop");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("Drink.Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("Drink.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drink.Domain.Entities.VerificationEmail", b =>
                {
                    b.HasOne("Drink.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_email_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminRole", b =>
                {
                    b.Navigation("MenuRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Drink.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Drink.Domain.Entities.Shop", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("EnabledIces");

                    b.Navigation("EnabledSizes");

                    b.Navigation("EnabledSugars");

                    b.Navigation("EnabledToppings");

                    b.Navigation("SugarOverrides");

                    b.Navigation("ToppingOverrides");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Drink.Domain.Entities.ShopMenuItem", b =>
                {
                    b.Navigation("Ices");

                    b.Navigation("Sizes");

                    b.Navigation("Sugars");

                    b.Navigation("Toppings");
                });

            modelBuilder.Entity("Drink.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
