name: .NET Build

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore api/Drink.sln

      - name: Build
        run: dotnet build api/Drink.sln --no-restore --configuration Release
